# Site/SEO settings
email: zhuqianze@pku.edu.cn
permalink: /:year/:month/:day/:title/
google_analytics: 

title: Qian-Ze Zhu
description: A second-year undergraduate in Department of Physics, Peking University, China.
url: "https://rosellaalucard.github.io/"
baseurl: ""
twitter_username: 
default_img: 

# Profile settings
name: Qian-Ze Zhu
profile_img: https://res.cloudinary.com/rosellaalucard/image/upload/v1562178799/avatar_u6jrpf.jpg
profile: A second-year undergraduate in Department of Physics, Peking University, China. Love all kinds of beautiful things.
social:
  github: RosellaAlucard

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
